image: docker:stable

services:
- docker:dind #Serviço para executar o docker dentro de uma imagem docker.

before_script:
- docker info #Pra garantir que o docker está executando, antes de qualquer script será executado esse comando docker.
- docker login -u $CI_REGISTRY_USER --password-stdin #Executa o login no Docker Hub pegando as variáveis de CI_REGISTRY_USER e CI_REGISTRY_PASSWORD de Settings -> CI/CD -> Variables, que foram previamente criadas lá.

build-docker:
  stage: build
  script:
    - docker build -t minha-imagem .
